Fix `exclude` variable default in bin script. (#14)
Prior to this change, calling `wi18n makepot` in a terminal would produce an error:
"options.exclude.push is not a function". The default value was being passed as an
empty string, instead of an empty array.